---
- hosts: localhost
  gather_facts: no

  tasks: 
  - name: Send Mail
    include_role:
      name: mail
    vars:
      mail_subject: "Your ELK Stack has been rolled out"
      mail_body: "{{ lookup('template', 'mail.j2') }}"

